@host = http://localhost:3031/api/
@user_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDc2MjY5NDMsImV4cCI6MTYwNzc5OTc0Mywic3ViIjoiMi1mYWxzZSJ9.fG9ySPm-3XnY4Xa9LX3692f73_a44Ay-bj0e_lypY5o
@auth_token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTI4ODg2MTksImV4cCI6MTYxMzA2MTQxOSwic3ViIjoiMS10cnVlLXRydWUifQ.qgrJMKKpT9mSf0lgPFRQ2VCsF4JgVrRESXafNvHzzjc

###

GET {{host}}users HTTP/1.1
Authorization: {{auth_token}}

###

POST {{host}}users HTTP/1.1
Content-Type: application/json
Authorization: {{auth_token}}

{
  "user": {
    "name": "lalal",
    "username": "lalalaFuncionario",
    "password": "123456"
  }
}

###

GET {{host}}users/2 HTTP/1.1
Authorization: {{auth_token}}

###

GET {{host}}users/2/orders HTTP/1.1
Authorization: {{auth_token}}

###

PUT {{host}}users/4 HTTP/1.1
Content-Type: application/json

{
  "user": {
    "name": "Ribeiro Editado",
    "is_active": true
  }
}
###

DELETE  {{host}}users/5 HTTP/1.1

###
